apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nginx-dev
    app.kubernetes.io/name: nginx
  name: nginx-dev
  namespace: dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  type: NodePort
  selector:
    app.kubernetes.io/instance: nginx-dev
    app.kubernetes.io/name: nginx